### ISSUE TITLE
Capitalization of 'Of' in the 'name'

### ISSUE THREAD

**Issue by JeremyMBell** [batashi/us-states-normalize#1]
The correct way to format the name of DC is "District of Columbia", but normalize says the name is "District Of Columbia". While it is the correct name, it is not the correct capitalization of a proper noun (articles and prepositions are lowercased in the name). You could also run into this issue with the "Federated States Of Micronesia".

http://www.aje.com/en/arc/editing-tip-capitalization-proper-and-common-nouns/

**Comment by kzylam** [comment]
Good point. Updated and pushed to new version.
